**ZESTAW 2:**

**Zad 1:**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 4, 3, 5, 3])
print(a.ndim)
b = np.array([3.14, 4, 2, 3], dtype=np.int32)
print(b.ndim)
c = np.array([[2,4,6],
              [1,2,3]])
print(c.ndim)
d = np.array([[-3.0,2.3],
              [0.1,5.0],
              [8.0,11.0]])
print(d.ndim)
e = np.array([[[[2,4],[1,2],[8,9]],
               [[7,6],[-3,4],[0,8]]]])
print(e.ndim)

e

1
1
2
2
4


array([[[[ 2,  4],
         [ 1,  2],
         [ 8,  9]],

        [[ 7,  6],
         [-3,  4],
         [ 0,  8]]]])

**Zad 2:**

funkcja shape() wypisuje wymiary macierzy!

In [ ]:

print("ndim: ", c.ndim)
print("shape: ", c.shape)
print("size: ", c.size)
print("dtype: ", c.dtype)
print("itemsize: ", c.itemsize)
print("nbytes: ", c.nbytes)
print("=============")
print("ndim: ", e.ndim)
print("shape: ", e.shape)
print("size: ", e.size)
print("dtype: ", e.dtype)
print("itemsize: ", e.itemsize)
print("nbytes: ", e.nbytes)

ndim:  2
shape:  (2, 3)
size:  6
dtype:  int64
itemsize:  8
nbytes:  48
ndim:  4
shape:  (1, 2, 3, 2)
size:  12
dtype:  int64
itemsize:  8
nbytes:  96


**Zad 3:**

In [ ]:
 X1 = np.random.random((4,3))
 X2 = np.zeros((2,1))
 X3 = np.full((6,2,1),2)
 X4 = np.random.randint(0,7,(5,8))
 X5 = np.eye(5)

 print(X1)
 print("======")
 print(X2)
 print("======")
 print(X3)
 print("======")
 print(X4)
 print("======")
 print(X5)


[[0.35156219 0.21610947 0.66852604]
 [0.97089457 0.17457109 0.1226613 ]
 [0.43760114 0.38299281 0.36515227]
 [0.34242551 0.28359437 0.29414475]]
[[0.]
 [0.]]
[[[2]
  [2]]

 [[2]
  [2]]

 [[2]
  [2]]

 [[2]
  [2]]

 [[2]
  [2]]

 [[2]
  [2]]]
[[4 5 5 3 0 3 5 1]
 [5 5 6 2 6 2 0 5]
 [5 1 1 2 6 1 3 0]
 [0 0 1 2 0 0 1 4]
 [3 2 6 4 1 5 5 4]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Odwołanie do konkretnego elementu tensora:

In [ ]:
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n cała tablica:")
print(X4)
print("======\n wiersz o indexie 4:")
print(X4[0]) # wiersz o indeksie 0
print("======\n element o indexach: [0,2]:")
print(X4[0,2]) # element o indexach 0 (wiersz) i 2 (kolumna)
print("======\n cała kolumna:")
print(X4[:,2]) # cała kolumna o indedksie 2
print("======\n cały wiersz:")
print(X4[3,:]) # cały wiersz o indedksie 3
print("======\n Minor macierzy:")
print(X4[1:3,2:5]) # wiersze: od indexu 1 do (3-1), kolumny: od indxu 2 do 4 

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 cała tablica:
[[4 5 5 3 0 3 5 1]
 [5 5 6 2 6 2 0 5]
 [5 1 1 2 6 1 3 0]
 [0 0 1 2 0 0 1 4]
 [3 2 6 4 1 5 5 4]]
 wiersz o indexie 4:
[4 5 5 3 0 3 5 1]
 element o indexach: [0,2]:
5
 cała kolumna:
[5 6 1 1 6]
 cały wiersz:
[0 0 1 2 0 0 1 4]
 Minor macierzy:
[[6 2 6]
 [1 2 6]]


**Zad 4:**

Liczenie shape - sprawdzamy ile w najbardziej zewnętrznym nawiasie jest elementów oddzielonych przecinkami. Potem wchodzimy do poszczególnego elementu i dalej sprawdzamy ile jest w nim elementów oddzielonych przecinkami. Itd.

In [ ]:
 A = np.random.randint(0,7,(4,5))
 A

array([[6, 2, 2, 3, 3],
       [6, 5, 4, 6, 3],
       [0, 0, 0, 3, 5],
       [1, 6, 6, 2, 3]])

In [ ]:
B = A[:,1:3]
B

array([[2, 2],
       [5, 4],
       [0, 0],
       [6, 6]])

In [ ]:
C = A[1:3,1:]
C

array([[5, 4, 6, 3],
       [0, 0, 3, 5]])

zmiana wartości danego elementu tensora:

**zmiana wartości w macierzy B powoduje zmianę w macierzy A**

In [ ]:
B[0,0]= 333
print(A)

[[  6 333   2   3   3]
 [  6   5   4   6   3]
 [  0   0   0   3   5]
 [  1   6   6   2   3]]


**stworzenie kopii tablicy:**


In [ ]:

C1 = A[1:3,1:].copy()
print("macierz A: \n", A, "\n")
C1[1,1] = 222
print("macierz C: \n", C1, "\n")
print("macierz A: \n", A, "\n")

macierz A: 
 [[  6 333   2   3   3]
 [  6   5   4   6   3]
 [  0   0   0   3   5]
 [  1   6   6   2   3]] 

macierz C: 
 [[  5   4   6   3]
 [  0 222   3   5]] 

macierz A: 
 [[  6 333   2   3   3]
 [  6   5   4   6   3]
 [  0   0   0   3   5]
 [  1   6   6   2   3]] 



**Zad 5:**

In [ ]:
D = np.array(np.arange(0,12))
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
print(D.reshape(2,6)) # stweorzenie macierzy [2,6]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
print(D.reshape(3,4)) # stweorzenie macierzy [3,4]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(D.reshape(1,3,4)) # dodanie zewnetrznego nawiasu:

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [ ]:
print(D.reshape(1,3,1,4,1))

[[[[[ 0]
    [ 1]
    [ 2]
    [ 3]]]


  [[[ 4]
    [ 5]
    [ 6]
    [ 7]]]


  [[[ 8]
    [ 9]
    [10]
    [11]]]]]


**Zad 6:**

**przy sklejaniu macierzy według odpowiedniej osi muszą zgadzać się (być równe) odpowiednie wymiary macierzy!**

In [ ]:
c = np.array([[2,4], [1,2]])
d = np.array([[-3,5],[-7,8]])

print("macierz c: \n",c)
print("=======")
print("macierz d: \n",d)

print("@@@@@@@@@@@@@@@@@@@@@@@@")
print(np.concatenate([c,d],axis=0)) # doklejenie od dołu
print("=========")
print(np.concatenate([c,d],axis=1)) # doklejenie z boku
print("=========")
print(np.concatenate([d,c],axis=0)) # doklejenie z dołu
print("=========")
print(np.concatenate([d,c],axis=1)) # doklejenie z boku


macierz c: 
 [[2 4]
 [1 2]]
macierz d: 
 [[-3  5]
 [-7  8]]
@@@@@@@@@@@@@@@@@@@@@@@@
[[ 2  4]
 [ 1  2]
 [-3  5]
 [-7  8]]
[[ 2  4 -3  5]
 [ 1  2 -7  8]]
[[-3  5]
 [-7  8]
 [ 2  4]
 [ 1  2]]
[[-3  5  2  4]
 [-7  8  1  2]]


**Zad 7:**

In [ ]:
print(d)
print("=========")
print(d+6)
print("=========")
print(d-8)
print("=========")
print(d*8) # mnożenie macierzy nie w sensie algebraiczym, ale mnożenie odpowiednich elementów macierzy przez siebie:
print("=========")
print(d/8)

[[-3  5]
 [-7  8]]
[[ 3 11]
 [-1 14]]
[[-11  -3]
 [-15   0]]
[[-24  40]
 [-56  64]]
[[-0.375  0.625]
 [-0.875  1.   ]]


In [ ]:
print(d)
print("=========")
print(abs(8))
print("=========")
print(np.exp(d))
print("=========")
print(np.power(d,4))
print("=========")
print(np.log(d))

[[-3  5]
 [-7  8]]
8
[[4.97870684e-02 1.48413159e+02]
 [9.11881966e-04 2.98095799e+03]]
[[  81  625]
 [2401 4096]]
[[       nan 1.60943791]
 [       nan 2.07944154]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in log
  if __name__ == '__main__':


**Zad 8:**

**jeśli chcemy dodać do siebie macierze o różnych wymiarach, to python rozszerzy mniejszą macierz, uzupełniając ją tymi samymi elementami, które już w niej się znajdują! = broadcasting**

In [ ]:
e = np.array([[0],[1],[2]])
print(e,"\n")

f = np.array([7,8,9])
print(f,"\n\n")

print(e+f)

[[0]
 [1]
 [2]] 

[7 8 9] 


[[ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]]
